# OpenAI Configuration
OPENAI_API_KEY=sk-proj-xxxxxxxxxxxxxxxxxxxx
MODEL_NAME=gpt-5-nano

# PostgreSQL Configuration
POSTGRES_URL=postgresql://user:password@localhost:5432/database

# REST API Configuration
REST_BASE_URL=

# SOAP API Configuration
SOAP_WSDL_URL=

# Browser Configuration
BROWSER_URL=https://xxxxx.com
BROWSER_USERNAME=Admin
BROWSER_PASSWORD=admin
PLAYWRIGHT_HEADLESS=true

# Python/UV Configuration
# (Optional) Overrides for dynamic path resolution
UV_PATH=
SITE_PACKAGES_PATH=
